# This is a config for E2B sandbox template.
# You can use template ID (5676ehngi6hh928vp4fo) or template name (vibe-nextjs-kasump) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-kasump") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-kasump") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-kasump')

team_id = "e78038e3-048a-45fd-8baa-d05d36a3c8a1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-kasump"
template_id = "5676ehngi6hh928vp4fo"
